name: Benchmark
on:
  push:
    branches:
      - main
jobs:
  Benchmark:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run benchmark
        run: cargo bench -- --output-format bencher > bench.txt
      - name: Create benchmark commit
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'cargo'
          output-file-path: bench.txt
          comment-on-alert: true
          fail-on-alert: true
          alert-threshold: '125%'
          alert-comment-cc-users: '@jofas'
          gh-pages-branch: main
          benchmark-data-dir-path: docs/dev/bench
      - name: Make commit
        uses: EndBug/add-and-commit@v9
        with:
          message: 'saving benchmark'
